config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'advisor#index'

  get 'begin' => 'advisor#begin'

  get 'genre' => 'advisor#genre'
  post 'genre' => 'advisor#genre'

  resources :movies do
    post 'like' => 'movies#like'
    post 'nope' => 'movies#nope'
    post 'seen_like' => 'movies#seen_like'
    post 'seen_nope' => 'movies#seen_nope'
  end 

  resources :relations do
    post 'remove' => 'relations#remove'
    post 'move_to_seen' => 'relations#moveToSeen'

  end 

  resources :users do
    get 'watchlist' => 'user#watchlist'
    get 'nopelist' => 'user#nopelist'
    get 'seenlist' => 'user#seenlist'
  end 
  
  

end

app/models/movie.rb
class Movie < ActiveRecord::Base
	has_many :users
	has_many :relations
	has_attached_file :picture, default_url: 'movie.png'
	validates_attachment_content_type :picture, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/relation.rb
class Relation < ActiveRecord::Base
	belongs_to :user
	belongs_to :movie
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :relations

end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_filters.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    before_filter :authenticate_admin

    def authenticate_admin
      redirect_to '/sign-in' unless current_user
    end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end

    def current_user
      return nil unless session[:current_user_id]
      User.find(session[:current_user_id])
    end
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = User.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   User.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/advisor_controller.rb
class AdvisorController < ApplicationController
  

  def index

  end

  def begin
  	@movies = Movie.all.order(score: :desc)
    @movies = @movies.first(20)
  	@relations = Relation.all.where user: current_user

  	@old_movies = []
  	@relations.each { |r| @old_movies << r.movie}

  	@new_movies = @movies - @old_movies

  	@first_movie = @new_movies.first
	
  end

  def genre
  	@genre = params['name']

  	if params['name'] == 'Any' || !params['name'].present?
  		redirect_to begin_path
  	else
  		@movies = Movie.all.where("genre like ?", "%"+ @genre +"%").order(score: :desc) if @genre.present?
      @movies = @movies.first(20)
	  	#@relations = Relation.all.where user: current_user

	  	#@old_movies = []
	  	#@relations.each { |r| @old_movies << r.movie}

	  	#@new_movies = @movies - @old_movies

	  	#@first_movie = @new_movies.first
	  	@first_movie = @movies.first


  	end

  	
  end

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  #before_action :authenticate_user!
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  

  def index

  	@movies = Movie.all
  end

  #relation related 

  def like
  	@movie = Movie.find(params[:movie_id])
    @movie.relations.create user: current_user, seen: false, like: true
  end

  def nope
  	@movie = Movie.find(params[:movie_id])
    @movie.relations.create user: current_user, seen: false, like: false 
  end

  def seen_like
    @movie = Movie.find(params[:movie_id])
    @movie.relations.create user: current_user, seen: true, like: true  
  end


  def seen_nope
  	@movie = Movie.find(params[:movie_id])
    @movie.relations.create user: current_user, seen: true, like: false  
  end

  #specific to movies
  def show
    @movie = Movie.find(params[:id])
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:id])
    @movie.update_attribute(:picture, params[:movie][:picture])

    redirect_to movie_path(@movie)
  end
  
end

app/controllers/relations_controller.rb
class RelationsController < ApplicationController

  #relation related 

  def remove
    Relation.find(params[:relation_id]).destroy
    redirect_to user_watchlist_path(current_user)
  end

  def moveToSeen
    Relation.find(params[:relation_id]).update seen: true

    redirect_to user_seenlist_path(current_user)
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :set_user

  def show
    @user = User.find(params[:id])
  end


  def watchlist
  	@watchlist = @user.relations.where seen: false, like: true 
  end

  def nopelist
  	@nopelist = @user.relations.where seen: false, like: false 
  end

  def seenlist
  	@seenlist = @user.relations.where seen: true
  end


  def set_user
  	@user = User.find(params[:user_id] || params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/black_jack_sessions_helper.rb
module BlackJackSessionsHelper
end

app/helpers/relations_helper.rb
module RelationsHelper
end

app/views/advisor/begin.html.erb
<div class="begin">
	<div class="top">
		<h3>Total mixed suggestions available: <%= @new_movies.count %></h3>
		<b> Would you like to watch...</b>
	</div>

	<% if @new_movies.present? && @new_movies.any? %>


		<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="false">
		  <!-- Indicators -->
			<ol class="carousel-indicators">
				<li data-target="#myCarousel" data-slide-to="0" class="active"></li>
				<li data-target="#myCarousel" data-slide-to="1"></li>
				<li data-target="#myCarousel" data-slide-to="2"></li>
				<li data-target="#myCarousel" data-slide-to="3"></li>
				<li data-target="#myCarousel" data-slide-to="4"></li>
				<li data-target="#myCarousel" data-slide-to="5"></li>
				<li data-target="#myCarousel" data-slide-to="6"></li>
				<li data-target="#myCarousel" data-slide-to="7"></li>
			</ol>

			<!-- Wrapper for slides -->
			<div class="carousel-inner" role="listbox">
				<%= render(@new_movies)%>
			</div>

		</div>
	<% end if%>

</div>

app/views/advisor/genre.html.erb
<div class="begin">
		<div class="top">
			<h3>Total <%= @genre %> suggestions available: <%= @movies.count %></h3>
			<b> Would you like to watch...</b>
		</div>
	<% if @movies.present? && @movies.any? %>

		<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="false">
		  <!-- Indicators -->
			<ol class="carousel-indicators">
				<li data-target="#myCarousel" data-slide-to="0" class="active"></li>
				<li data-target="#myCarousel" data-slide-to="1"></li>
				<li data-target="#myCarousel" data-slide-to="2"></li>
				<li data-target="#myCarousel" data-slide-to="3"></li>
				<li data-target="#myCarousel" data-slide-to="4"></li>
				<li data-target="#myCarousel" data-slide-to="5"></li>
				<li data-target="#myCarousel" data-slide-to="6"></li>
				<li data-target="#myCarousel" data-slide-to="7"></li>
			</ol>

			<!-- Wrapper for slides -->
			<div class="carousel-inner" role="listbox">
				<%= render(@movies)%>
			</div>

		</div>

	<% else %>
		<%= @movies%>
		<h3>Sorry no results for <%= @genre %></h3>
	<% end if%>

</div>

app/views/advisor/index.html.erb
<div class="intro">

	<% if user_signed_in? %>
		<div class="begin-form">
			<%= form_tag genre_path do %>
			    <%=label_tag 'Choose a movie genre:' %>
			    <%= select_tag('name', options_for_select([['Any'],['Action'], ['Adventure'], ['Comedy'], ['Crime'],  ['Drama'], ['Family'], ['Fantasy'], ['Historical'], ['Horror'], ['Mystery'], ['Thriller'], ['Romance'], ['Sci-Fi'],]), style: 'margin-bottom: 15px;') %>

			    <div><%= submit_tag "▷ Begin your experience", style: 'background: white;' %></div>
			<% end -%>


		</div>
		
	<% else %>
		<div class="logged-out">
			<h2> Please login to continue.</h2>
			<%= link_to "Sign up", new_user_registration_path, :class => 'btn btn-default'  %>
			<%= link_to "Login", new_user_session_path, :class => 'btn btn-default'  %>
		</div>

	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Movie Advisor</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body style="background: black">
	<nav class="navbar navbar-inverse bg-inverse">
	  <div class="container-fluid">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand" href="/">Movie Advisor</a>
	    </div>

	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav">
	        <li class="<% 'active' if current_page?(root_path) %>"><a href="/">Home <span class="sr-only">(current)</span></a></li>
	        <% if user_signed_in? %>
		        <li class="dropdown">
		          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Browse <span class="caret"></span></a>
		          <ul class="dropdown-menu bg-inverse">
		            <li><a href="<%= user_watchlist_path(current_user) %>">Up next list</a></li>
		            <li><a href="<%= user_nopelist_path(current_user) %>">Dislikes</a></li>
		            <li><a href="<%= user_seenlist_path(current_user) %>">What I've seen</a></li>
		            <li role="separator" class="divider"></li>
		            <li><a href="/begin">Get a Suggestion</a></li>
		            <li role="separator" class="divider"></li>
		            <li><a href="#">More</a></li>
		          </ul>
		        </li>
	        <% end %>

	      </ul>
	      <ul class="nav navbar-nav navbar-right" style="color: white">
	        <h1></h1>
	        <% if user_signed_in? %>
			  Logged in as <strong><%= current_user.email %></strong>.
			  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
			  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
			<% else %>
			  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
			  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
			<% end %>
	      </ul>
	    </div><!-- /.navbar-collapse -->
	  </div><!-- /.container-fluid -->
	</nav>

	<% if notice %>
	  <p class="alert alert-success"><%= notice %></p>
	<% end %>
	<% if alert %>
	  <p class="alert alert-danger"><%= alert %></p>
	<% end %>

	<%= yield %>

</body>
</html>

app/views/movies/_movie.html.erb
<div class="item suggestion <%= "active" if movie.id == @first_movie.id %>">
	<div class="info">
	</div>


	<blockquote class="embedly-card" data-card-controls="0"><h4><a class="movie-image" href="<%= movie.link %>/image"><%= movie.title %> (<%= movie.year %>)</a></h4><p>Imdb Score: <%= movie.score %></p></blockquote>
	<script async src="//cdn.embedly.com/widgets/platform.js" charset="UTF-8"></script>

	<div class="movie-link">
		<a href="<%= movie_path(movie) %>">More about this movie</a>
	</div>


	<div class="buttons">
		<%= link_to "✔ Yes", movie_like_path(movie), :method => :post, class: "like btn btn-default" , remote: true, :'data-target' => "#myCarousel", :'data-slide' =>"next" %>
		<%= link_to "X No", movie_nope_path(movie), :method => :post, class: "nope btn btn-default" , remote: true, :'data-target' => "#myCarousel", :'data-slide' =>"next"  %>
		<%= link_to "SEEN IT", movie_seen_like_path(movie), :method => :post, class: "btn btn-default", remote: true, :'data-target' => "#myCarousel", :'data-slide' =>"next" %>
	</div>
	
</div>

app/views/movies/edit.html.erb
<div class="carousel-caption">
	<img src="<%= @movie.picture.url %>" alt="<%= @movie.title %>" style="height: 400px">
	<p><%= @movie.title %></p>
	<%= link_to 'Back to movie page', movie_path(@movie) %>
</div>

<div class="update">
	<h3>Update Movie Info</h3>
	<%= form_for @movie, :url => {:action => 'update'}, :html => { :multipart => true } do |form| %>
	  <p>Title</p>
	  <%= form.text_field :title %>
	  <p>Year</p>
	  <%= form.number_field :year %>
	  <p>Rating (%)</p>
	  <%= form.text_field :rating %>
	  <p>Picture</p>
	  <%= form.file_field :picture %>
	  <br>
	  <%= form.submit "update" %>
	<% end %>
</div>

app/views/movies/index.html.erb
<div class="movie-list">
	
	<h3>There are current <%= @movies.count %> available for suggestions on the app.</h3>


</div>

app/views/movies/show.html.erb
	<div class="read-more">
		

		<h3><%= @movie.title %></h3>
		<p><%= @movie.year %></p>
		<p>Imdb Score: <%= @movie.score %></p>

		<a href="http://www.canistream.it/search/movie/<%= @movie.title%>" class="btn btn-default" target="_blank">Can I stream it?</a>

	</div>

app/views/relations/_relation.html.erb
	<div class="relation">
		<% if relation.present? %>
			<a href="<%= movie_path(relation.movie)%>"><div class="container"><p><%= relation.movie.title %>(<%= relation.movie.year%>)</p></div></a>
			<% if !relation.seen && relation.like %>
				<%= link_to "➥ Seen", relation_move_to_seen_path(relation), :method => :post, class: "btn btn-default seen-btn" , remote: true, style: "color: black" %>
			<% end %>
				<%= link_to "✕ Remove", relation_remove_path(relation), :method => :post, class: "btn btn-danger remove-btn", style: "color: black" %>
		<% else %>
			<p>?</p>
		<% end %>
	</div>

app/views/user/_user.html.erb
	<h2><%= user.name %></h2>

	<div class="watch-list">
		<h3>You liked:</h3>
		<p>User email: <%= user.email %></p>
		<p>User Created on: <%= user.created_at %></p>
	</div>

app/views/user/index.html.erb
<% if flash[:notice] %>
	<div class="failFlash">
	    <div class="notice"><%= flash[:notice] %></div>
	</div>
<% end %>

app/views/user/nopelist.html.erb
<div class="nope-list">	
	<% if @nopelist.any? %>
		<h3>You said you dont wanna watch: </h3>
		<%= render @nopelist %>
	<% else %>
		<h3>Your dislike list is empty</h3>
	<% end %>
</div>

app/views/user/seenlist.html.erb
<div class="seen-list">
	<% if @seenlist.any? %>
		<h3>You've seen:</h3>
		<%= render @seenlist %>
	<% else %>
		<h3>You havent seen any of our movie list.</h3>
	<% end %>
</div>

app/views/user/show.html.erb
	<div class="watch-list">
		<%= render @user %>
	</div>

app/views/user/watchlist.html.erb
<div class="watch-list">
	<% if @watchlist.any? %>
		<h3>You liked:</h3>
		<%= render @watchlist %>
	<% else %>
		<h3>Your watch list is empty.</h3>
	<% end %>
</div>